small_test:
  lambda: 0.75
  mu: 0.15
  servers: 10
  queue_cap: 0
  theta_i_max: 3
  budget_min: 5       # Start of the sequence
  budget_max: 100      # End of the sequence
  n_budgets: 10   # Number of points in the sequence
  budget_log: 2 # Controls spacing of the evaluated budgets
  num_obs: 10
  warmup: 10
  sim_length: 100
  results_directory: Results/numerical_experiments/repair_budget_sensitivity_analysis

large_test:
  lambda: 3.25
  mu: 0.15
  servers: 25
  queue_cap: 5
  theta_i_max: 8
  budget_min: 5       # Start of the sequence
  budget_max: 1200      # End of the sequence
  n_budgets: 40   # Number of points in the sequence
  budget_log: 2 # Controls spacing of the evaluated budgets
  num_obs: 10
  warmup: 10
  sim_length: 100
  results_directory: Results/numerical_experiments/repair_budget_sensitivity_analysis